apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: taka-webapp
  labels:
    app: taka-webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taka-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taka-webapp
    spec:
      containers:
      - image: gcr.io/k8s-aksels/github-takaapp-web-application:v0.3.1
        imagePullPolicy: Always
        name: frontend-shortener
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
